### ISSUE TITLE
display-plugin-updates does not recognize enforced maven version 

### ISSUE THREAD

**Issue by joergsesterhenn** [mojohaus/versions-maven-plugin#285] opened 2018-06-20 08:41 UTC
Since maven 3.5.x there is a warning that prerequisites-Tags are for plugin-Projects only.
So I changed our Enterprise-Parent-POM project to enforce maven 3.0.5 like this :

  ```
  <build> 
   <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>3.0.0-M2</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>enforce-releases-maven-java</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <requireReleaseDeps>
                  <onlyWhenRelease>true</onlyWhenRelease>
                  <message>Snapshots sind als dependency nicht zugelassen!</message>
                  <level>ERROR</level>
                </requireReleaseDeps>
                <requireMavenVersion>
                  <version>3.0.5</version>
                  <level>ERROR</level>
                  <message>Bitte verwenden Sie Maven ab Version 3.0.5.</message>
                </requireMavenVersion>
                <requireJavaVersion>
                  <version>1.8.0</version>
                  <level>WARN</level>
                  <message>Bitte verwenden Sie Java ab Version 8.</message>
                </requireJavaVersion>
              </rules>    
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

The versions-plugin fails to recognize this and states

> [WARNING] Project does not define minimum Maven version, default is: 2.0
> [INFO] Plugins require minimum Maven version of: 3.0.5
> [INFO] 
> [ERROR] Project does not define required minimum version of Maven.
> [ERROR] Update the pom.xml to contain maven-enforcer-plugin to
> [ERROR] force the maven version which is needed to build this project.
> [ERROR] See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
> [ERROR] Using the minimum version of Maven: 3.0.5
> [INFO] 
> [INFO] Require Maven 2.0.1 to use the following plugin updates:

**Comment by adamvoss** [comment] 2018-06-29 19:15
Duplicate of #48.  Vote on #269 about getting it released.

**Comment by Godin** [comment] 2018-10-03 16:11
Closing as duplicate.

**Closed by Godin** 2018-10-03 16:11 UTC
Labels: duplicate
