### ISSUE TITLE
[Feature-Request] mvn version:display-dependency-updates --limit <dependency> to check only a specific dependency

### ISSUE THREAD

**Issue by tillmannheigel** [mojohaus/versions-maven-plugin#212] opened 2017-09-25 13:54 UTC
It would be great to have an option thats limits version checks for a single dependency (or a group, or a group pattern). 

Especially for large projects or slow repositories it's annoying to check all dependency everytime. 

I will open a PR as soon as possible.

**Comment by rsrini7** [comment] 2020-05-15 08:52
2.5 Years + Old issue.  Any resolution ?
Each commit, jenkins takes 20 mins to check all irrelevant repos checking.

**Comment by tillmannheigel** [comment] 2020-05-24 18:18
Thx for the reminder.

**Comment by naiyerasif** [comment] 2020-07-01 18:06
This is the single most important reason why I'm not using this plugin in my projects. It takes way too long to finish, especially in case of large dependency graphs and multiple Maven profiles.

I'd suggest a way to configure the **depth** of dependency scan that this plugin should do (e.g., a `depth = 0` should only show me the updates applicable for the dependencies explicitly mentioned in the POM of the current project). In case of a BOM, I'd like to restrict the scan to limit to what versions the BOM dictates.

**Comment by somejavadev** [comment] 2021-01-23 12:32
@tillmannheigel @rsrini7 @naiyerasif 

I also require this functionality. I have made a pull request so long but you are more than happy to try it out. The new parameter is called includes (similar to the dependency tree plugin) 

```bash
mvn versions:display-dependency-updates -Dincludes=org.springframework.boot:spring-boot-starter-data-jpa,org.hibernate
```

**Comment by tillmannheigel** [comment] 2021-01-26 17:43
Thx a lot, I kind of lost track :)

**Comment by somejavadev** [comment] 2021-01-27 11:06
@tillmannheigel Not a problem at all. It is the first time I am contributing to this project so there might be some changes required to my PR. I am however using the PR version without any problems.

**Comment by drypycode** [comment] 2022-01-27 15:12
@somejavadev Any updates on this issue? I'd be happy to chip in to get this over the finish line if I can

**Comment by ajarmoniuk** [comment] 2022-09-04 19:30
Working on it :smile:

**Comment by ajarmoniuk** [comment] 2022-09-04 19:37
Duplicate of #318

**Closed** 2022-09-04 19:43 UTC

**Comment by somejavadev** [comment] 2022-09-05 06:40
@drypycode apologies for the late reply but I see @ajarmoniuk already replied.
