### ISSUE TITLE
allowMinorUpdates property of update-properties doesn't work correctly.

### ISSUE THREAD

**Issue by xjj59307** [mojohaus/versions-maven-plugin#164] opened 2017-06-05 07:52 UTC
Version 2.4 introduced allowxxx properties for update-properties.

`mvn versions:update-properties -DallowSnapshots=true -DallowMajorUpdates=false -DallowMinorUpdates=false`

is possible to update a property from 1.0.0 to 1.1.0-SNAPSHOT while minor update is disabled.

Is this behavior intentional?

**Comment by khmarbaise** [comment] 2017-06-05 09:19
You have defined to prevent minor updates so that the property is not updated looks from my point of views as works as intended...If you like to get an update in this situation you have to omit `-DallowMinorUpdates=false`?

**Comment by xjj59307** [comment] 2017-06-05 11:58
@khmarbaise Version could be updated from 1.0.0 to 1.1.0-SNAPSHOT even when minor update is disabled with `-DallowMinorUpdates=false`.

I traced the code a little bit. The upper bound is set to a release version (1.1.0) and then the release version(1.1.0-SNAPSHOT) will be chosen because it is lower than the release version.

https://github.com/mojohaus/versions-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/versions/api/PropertyVersions.java#L360

**Comment by khmarbaise** [comment] 2017-06-05 12:10
Ah Ok..I think omitting `-DallowSnapshots=true` would help but does only cover the real issue here...It looks like I missed to use the [filter](https://github.com/mojohaus/versions-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/versions/ordering/MajorMinorIncrementalFilter.java) which is already used in `use-latest-release` and `use-latest-versions`...to handle such situations...

**Comment by rdellar** [comment] 2017-06-05 21:00
We had a similar issue in our builds.  I was curious if your change might fix this issue also?

We updated to 2.4 and were using this command to pull in the latest minor release updates:
```
mvn -B -U clean org.codehaus.mojo:versions-maven-plugin:2.4:use-latest-versions '-Dincludes=com.something,com.something.*' -DallowSnapshots=false -DallowMajorUpdates=false
```

However it would not upgrade certain SNAPSHOT versions to their corresponding release versions that existed in Nexus...

We rolled the command back to 2.3 and it started working / updated dependencies again:
```
mvn -B -U clean org.codehaus.mojo:versions-maven-plugin:2.3:use-latest-versions '-Dincludes=com.something,com.something.*' -DallowSnapshots=false -DallowMajorUpdates=false
```

Thanks in advance.

**Comment by xjj59307** [comment] 2017-06-06 00:19
Hi, @rdellar 

My fix is only for the goal of update-properties.
As for what you commented, I don't think use-latest-versions could downgrade a version from 1.1.0-SNAPSHOT to 1.0.0, or are you meaning 1.1.0? If that's the case, I think it's better to create another issue. And just FYI, why not have a try on [use-releases](http://www.mojohaus.org/versions-maven-plugin/use-releases-mojo.html).

**Comment by rdellar** [comment] 2017-06-06 02:33
Sorry about that.  I fixed the note, but yes I meant widget-1.1.0-SNAPSHOT to widget-1.1.0...  Or it could be widget-1.1.0-SNAPSHOT to widget-1.3.0, if 1.3.0 was the latest release version.  (Basically we just want to update all dependencies to the latest minor release version.  Most of these are dependencies that we have created ourselves in-house, but some are external.)

We can try use-releases, but I didn't think it would go to the latest release like use-latest-versions used to do for us.  I will try to get a cleaner example and post if I can get one.  (All I know for now is that reverting to 2.3 fixed our problem.)

**Comment by khmarbaise** [comment] 2017-06-06 19:02
First I'm reading through this thread taking a look on this:

> Version could be updated from 1.0.0 to 1.1.0-SNAPSHOT even when minor update is disabled with -DallowMinorUpdates=false.

This is something I wouldn't expect. Cause based on the given limit it should **not** update the versions to 1.1.0-SNAPSHOT. Apart from that it will be limited by `allowSnapshots=true/false`...

In the end based on the start of this issue I think it works correctly...cause we are talking about `update-properites` goal?

Furthermore can we keep on the subject if this issue and not seeding other issues into this issue otherwise it is impossible to follow and keep the different lines of problems separated. If there other goals having issues please make a different issue for that....

**Comment by glianeric** [comment] 2017-06-06 20:38
I agree: with minor updates suppressed it should not look for versions other than 1.0.z[-SNAPSHOT] from the example above.

**Comment by rdellar** [comment] 2017-06-06 20:42
I'll make a separate thread for my issue.  It is in a different goal, but appeared related since it has to do with the same -Dallow flags not upgrading.

**Comment by mtanamiAtCisco** [comment] 2017-06-12 11:49
Hi,
I admit I'm a bit confused here.. I also use "update-properties" goal and allowMinorUpdates=false is not preventing the change of minor (meaning: 1.0.0 changing to 1.1.0 although it shouldn't). 
Is this the problem resolved or not? Is that the thread I should follow for updates in this matter? 
Thanks, 
Moria

(I'm using maven 3.2.1 and versions-maven-plugin version 2.4)

**Comment by xjj59307** [comment] 2017-06-13 01:45
@mtanamiAtCisco 

Did you specify -DallowMajorUpdates=false also? If not, allowMinorUpdates would not work.

**Comment by mtanamiAtCisco** [comment] 2017-06-13 06:27
@xjj59307 yes, specified both. 
this is my configuration: 
`<goals>
							<goal>update-properties</goal>
						</goals>
						<configuration>
							<includes>
								<include>my.group.*:*</include>
							</includes>
							<allowMajorUpdates>false</allowMajorUpdates>
							<allowMinorUpdates>false</allowMinorUpdates>
							<allowSnapshots>true</allowSnapshots>
							<processDependencies>true</processDependencies>
						</configuration>`
Is that working properly for you?

**Comment by xjj59307** [comment] 2017-06-14 03:25
@mtanamiAtCisco 
It could be a bug for 2.4 version according to @rdellar. You may have a try on version 2.3.

**Comment by mtanamiAtCisco** [comment] 2017-06-14 05:57
Version 2.3 doesn't support updating properties as proper. It changes both major and minor version. 
@khmarbaise can you advice?

**Comment by xjj59307** [comment] 2017-06-14 06:57
@mtanamiAtCisco

Btw, I found a bug that update-properties could update the property to a snapshot version, rather than a release version. And I have created a [patch](https://github.com/xjj59307/versions-maven-plugin/commit/d054bd718b06f5cb1f1ce37a3f6ead176576810f) for it.

**Comment by mtanamiAtCisco** [comment] 2017-06-14 07:03
Hi, 

In my example I do allowSnapshots, so no issue on that.

**Comment by khmarbaise** [comment] 2017-06-15 10:25
First If you have a configuration for versions-maven-plugin in your pom you have to be aware that running versions-maven-plugin is done calling like `versions:update-properties ...` which means no lifecycle is running. So you have to do the configuration in special way:
```
<project...>
 ... 
  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>versions-maven-plugin</artifactId>
        <version>2.4</version>
        <executions>
          <execution>
            <id>default-cli</id>
            <configuration>
                <... The configuration you would like give here ..>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins> 
  </build>
</project>
```
The most important part is using the id `default-cli` which is used in cases where the plugin is called via a goal and running within the lifecycle.

Apart from that if you like to update a property to a SNAPSHOT you must check if this is in reality a downgrade like from version `1.0.0` to `1.0.0-SNAPSHOT` cause based on the timeline how versions are generated and used `1.0.0-SNAPSHOT` is done before `1.0.0`. In such cases you have to give `-DallowDowngrade=true` otherwise this will not happen. If you like to check how the order for version is you can check that via Maven:
```
~$ java -jar  /.../apache-maven-3.3.9/lib/maven-artifact-3.3.9.jar 1.0.0 1.0.0-SNAPSHOT
Display parameters as parsed by Maven (in canonical form) and comparison result:
1. 1.0.0 == 1
   1.0.0 > 1.0.0-SNAPSHOT
2. 1.0.0-SNAPSHOT == 1-snapshot
```
Here you can see that Maven defined `1.0.0` being greater than `1.0.0-SNAPSHOT`...

**Comment by khmarbaise** [comment] 2017-06-15 10:57
So in the end my conclusion here is: There is no issue with that?

**Comment by mtanamiAtCisco** [comment] 2017-06-18 08:25
when adding <id>default-cli</id> it is working as expected :)
Thank you Karl!

**Comment by khmarbaise** [comment] 2017-06-18 08:42
So this means it is not a bug. I will close the issue. If you have further problems please don't hesitate to open a issue here...

**Closed by khmarbaise** 2017-06-18 08:42 UTC
