### ISSUE TITLE
Plugin fails with "Illegal character in path" if sub-module references ${project.groupId}

### ISSUE THREAD

**Issue by cowwoc** [mojohaus/versions-maven-plugin#332] opened 2019-02-15 20:34 UTC
Version 2.7
Maven 3.6.0

[testcase.zip](https://github.com/mojohaus/versions-maven-plugin/files/2870771/testcase.zip)

Repro steps:
1. Extract testcase
2. Run "mvn versions:display-dependency-updates versions:display-plugin-updates versions:display-property-updates"
3. Plugin will fail with:

```
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.7:display-plugin-updates (default-cli) on project submodule: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.7:display-plugin-updates failed: Illegal character in path at index 38: https://repo.maven.apache.org/maven2/${project/groupId}/test/maven-metadata.xml -> [Help 1]
```

4. Notice that `~/.m2/${project/groupId}/test` is created

Expected behavior:

1. `${project.groupId}` should result to `testcase`
2. Repository directory should not be created

**Comment by nicolasbarbier** [comment] 2019-10-01 10:28
I have the same problem, with a similar set-up (using a plugin with <groupId>${project.groupId}</groupId>, because the plugin uses the same versioning system as the parent POM and the other submodules). It seems that property-replacement is not performed in this case.

**Comment by ajarmoniuk** [comment] 2022-09-17 04:18
Cannot reproduce anymore. I guess this must have been fixed. I suggest to close this. @slachiewicz

**Closed** 2022-09-17 07:20 UTC

**Comment by cowwoc** [comment] 2022-09-18 02:34
@ajarmoniuk What (released) versions did you test this against?

**Comment by ajarmoniuk** [comment] 2022-09-18 04:47
2.12.0, but now I've also tried with 2.7.0 and didn't see the error either. Could you please retest and attach the output with the -X switch? 

Btw, you don't need to run display-dependency-updates or display-property updates if they're not the ones that are failing.
