### ISSUE TITLE
versions:update-parent not updating pom ? 

### ISSUE THREAD

**Issue by alainkr** [mojohaus/versions-maven-plugin#41] opened 2015-11-23 23:01 UTC
Hello,

I'm doing : 

 mvn -X versions:update-parent  "-DparentVersion=[0.8]"

Log says 

[DEBUG] Proposal is to update from 1.0.0-SNAPSHOT to 0.8
[INFO] Updating parent from 1.0.0-SNAPSHOT to 0.8
[DEBUG] Made an update from 1.0.0-SNAPSHOT to 0.8

But no pom is actually updated. I'm I missing something ? 

Thanks

**Comment by khmarbaise** [comment] 2017-05-22 19:50
Have retried your use case with versions-maven-plugin version 2.3 which works fine. So I can't reproduce your problem. So I will close the issue. If you have further details etc. please don't hesitate to reopen the issue.

**Closed by khmarbaise** 2017-05-22 19:50 UTC
