### ISSUE TITLE
update-parent in 2.12.0 no longer respects allowSnapshots parameter

### ISSUE THREAD

**Issue by llengo-pl** [mojohaus/versions-maven-plugin#720] opened 2022-09-22 13:46 UTC
In 2.12.0 `allowSnapshots` parameter is overridden by hardcoding `allowingSnapshots` to `false` [here](https://github.com/mojohaus/versions-maven-plugin/blob/e2c7dcadf335c747bb4dc77ee42c10bb79a3106a/src/main/java/org/codehaus/mojo/versions/UpdateParentMojo.java#L137). So the snapshot parent versions will be filtered out and a desired version is not found when one tries to update-parent to a snapshot version.

Since on master branch I see that UpdateParentMojo is changed quite substantially, and that allowingSnapshots param was reverted to `null`, I am created this issue just as a note so other users know that a problem exists.

**Comment by ajarmoniuk** [comment] 2022-09-22 13:49
Duplicate of #670.

@slachiewicz

**Closed** 2022-09-22 13:51 UTC

**Comment by llengo-pl** [comment] 2022-09-22 13:53
Apologies for the duplicate, I've looked through the issues before posting but it just didn't occur to me that the issue would be closed.
