### ISSUE TITLE
Remove deprecating message in rules documentation

### ISSUE THREAD

**Issue by pbougrier** [mojohaus/versions-maven-plugin#302] opened 2018-08-29 12:55 UTC
Offending page: http://www.mojohaus.org/versions-maven-plugin/version-rules.html
As of #157 (closed), rules will remains. So the message on top of the documentation can be removed

**Comment by oliverlockwood** [comment] 2018-10-31 09:38
There are also deprecation notices in http://www.mojohaus.org/versions-maven-plugin/xsd/rule-2.0.0.xsd and http://www.mojohaus.org/versions-maven-plugin/rule.html which should be removed, similarly.

**Comment by chabala** [comment] 2019-10-18 14:52
This looks like a duplicate of https://github.com/mojohaus/versions-maven-plugin/pull/273 which is already referenced in #157.

Not sure when there will be a release to publish the change.

**Closed** 2021-09-11 14:49 UTC
