### ISSUE TITLE
versions:display-plugin-updates doesn't take parent pom build.plugins.plugin versions into account

### ISSUE THREAD

**Issue by jonenst** [mojohaus/versions-maven-plugin#131] opened 2017-02-16 16:41 UTC
I have a structure:
parent/pom.xml
parent/child/pom.xml

When a plugin in the parent version is not in the build.pluginManagement.plugins.plugin element, it is not picked up by version:display-plugin-updates in the child.

tested with maven 3.0.5 and 3.3.9; maven-versions-plugin 3.0.0, 3.0.1, 3.0.2

How is this supposed to be used ?

For example:  
good/parent/pom.xml:
```xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>foo</groupId>
  <artifactId>parent</artifactId>
  <name>parent pom</name>
  <packaging>pom</packaging>
  <version>1.0.0</version>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
      </plugin>
    </plugins>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  <prerequisites>
    <maven>3.0.5</maven>
  </prerequisites>
</project>
```
good/parent/child/pom.xml
```xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>foo</groupId>
  <artifactId>child</artifactId>
  <name>child pom</name>
  <packaging>pom</packaging>
  <version>1.0.0</version>
  <parent>
    <groupId>foo</groupId>
    <artifactId>parent</artifactId>
    <version>1.0.0</version>
  </parent>
</project>
```
$ mvn versions:display-plugin-updates
```
[INFO] --- versions-maven-plugin:2.3:display-plugin-updates (default-cli) @ child ---
[INFO] 
[INFO] All plugins with a version specified are using the latest versions.
[INFO] 
[WARNING] The following plugins do not have their version specified:
[WARNING]   maven-deploy-plugin ....................... (from super-pom) 2.8.2
[WARNING]   maven-install-plugin ...................... (from super-pom) 2.5.2
[WARNING]   maven-site-plugin ........................... (from super-pom) 3.6
```

Compare with:
bad/parent/pom.xml:
```xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>foo</groupId>
  <artifactId>parent</artifactId>
  <name>parent pom</name>
  <packaging>pom</packaging>
  <version>1.0.0</version>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <version>3.0.0</version>
      </plugin>
    </plugins>
  </build>
  <prerequisites>
    <maven>3.0.5</maven>
  </prerequisites>
</project>

```
bad/parent/child/pom.xml  is the same as good/parent/child/pom.xml

$ mvn versions:display-plugin-updates
```
[INFO] --- versions-maven-plugin:2.3:display-plugin-updates (default-cli) @ child ---
[INFO] 
[INFO] All plugins with a version specified are using the latest versions.
[INFO] 
[WARNING] The following plugins do not have their version specified:
[WARNING]   maven-clean-plugin ........................ (from super-pom) 3.0.0
[WARNING]   maven-deploy-plugin ....................... (from super-pom) 2.8.2
[WARNING]   maven-install-plugin ...................... (from super-pom) 2.5.2
[WARNING]   maven-site-plugin ........................... (from super-pom) 3.6
```

**Comment by khmarbaise** [comment] 2017-02-26 15:53
First I would say not defining plugin versions in pluginManagement is not the best but on the other hand this could be improved ...

**Comment by cstamas** [comment] 2017-05-05 07:33
Similar situation here:
parent (external) defines a plugin with version and some config
project parent defines the plugin in pluginMgt w/o version and alternate config
child uses plugin w/o version

While effective pom of child shows version, the mojo reports the plugin as having "unspecified" version, which IMO is wrong.

Is it recommendation, to not have pluginMgt entry without version, even if parent has it w/ version?

**Comment by rvsasseen** [comment] 2018-06-19 18:06
I have basically the same issue, and a second related issue.
The parent pom specifies a plugin in plugins (but not pluginManagement) with version.
```
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-clean-plugin</artifactId>
				<version>3.0.0</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.6.1</version>
                                ...
```
The project pom does not specify any plugins. The versions plugin does not pick up on the version specs in the build.plugins section, but it should. 
```
$ mvn versions:display-plugin-updates
[INFO] All plugins with a version specified are using the latest versions.
[WARNING] The following plugins do not have their version specified:
[WARNING]   maven-clean-plugin ........................ (from super-pom) 3.0.0
[WARNING]   maven-compiler-plugin ..................... (from super-pom) 3.7.0
```
If I add the plugin groupId/artifactId/version pluginManagement,
```
	<build>
		<pluginManagement>
			<plugins>
                                <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-clean-plugin</artifactId>
                                        <version>3.0.0</version>
                                </plugin>
                                <plugin>
                                        <groupId>org.apache.maven.plugins</groupId>
                                        <artifactId>maven-compiler-plugin</artifactId>
                                        <version>3.6.1</version>
                                </plugin>
```
I don't get the warnings about the compiler and clean plugins. So the versions plugin is not paying attention to the build.plugins section, only to the build.pluginManagement.plugins section, which seems like a clear bug.

The second issue is that after the change, the versions plugin is still saying 
```
[INFO] All plugins with a version specified are using the latest versions.
```
even though the compiler plugin is not specifying the latest version, 3.6.1 vs 3.7.0.
This also seems like a clear bug.

**Comment by lprimak** [comment] 2022-01-01 05:42
Please reopen this issue. This is clearly a bug.

Furthermore, there is no way to determine outdated plugins that are specified in `pluginManagement` whatsoever with the versions plugin

**Comment by rvsasseen** [comment] 2022-01-01 07:08
Agree. The issue is called stale, but it should be easy enough for the development team to verify whether it still exists, and if people are still commenting on it, presumably it does. One would think it wouldn't be that hard to fix. Maybe it's not considered a high priority, but why not leave it open until the team can eventually get to it?

________________________________

**Comment by stefanseifert** [comment] 2022-02-17 15:30
i assume this is a duplicate of #550, #562 is my proposal to fix the issue
see also https://github.com/mojohaus/versions-maven-plugin/issues/550#issuecomment-1043068835 about my rationale for the fix

**Comment by ajarmoniuk** [comment] 2022-10-07 05:54
I've been trawling through the oldest bugs trying to fix them. However, I'm unable to reproduce this one, even with version 2.7 of the plugin. @lprimak could you please provide steps to reproduce it if you believe it should still be open?

**Comment by lprimak** [comment] 2022-10-07 18:26
Tried to reproduce with 2.11 (latest maven) and the issue looks to be fixed. thank you! @ajarmoniuk

**Comment by ajarmoniuk** [comment] 2022-10-07 18:30
@slachiewicz can be closed

**Closed** 2022-10-07 19:26 UTC
