### ISSUE TITLE
Use-latest-releases can't load custom rule set file

### ISSUE THREAD

**Issue by rsandell** [mojohaus/versions-maven-plugin#35] opened 2015-10-28 14:07 UTC
command: `mvn -X org.codehaus.mojo:versions-maven-plugin:2.2:use-latest-releases -DallowMajorUpdates=false -Dmaven.version.rules=/home/rsandell/rules.xml`

Error:

```
[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.2:use-latest-releases (default-cli) on project the-project: Could not load specified rules from /home/rsandell/rules.xml: File: /rules.xml does not exist -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.2:use-latest-releases (default-cli) on project the-project: Could not load specified rules from /home/rsandell/rules.xml
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Could not load specified rules from /home/rsandell/rules.xml
    at org.codehaus.mojo.versions.api.DefaultVersionsHelper.loadRuleSet(DefaultVersionsHelper.java:342)
    at org.codehaus.mojo.versions.api.DefaultVersionsHelper.<init>(DefaultVersionsHelper.java:206)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.getHelper(AbstractVersionsUpdaterMojo.java:214)
    at org.codehaus.mojo.versions.AbstractVersionsDependencyUpdaterMojo.toArtifact(AbstractVersionsDependencyUpdaterMojo.java:211)
    at org.codehaus.mojo.versions.UseLatestReleasesMojo.useLatestReleases(UseLatestReleasesMojo.java:140)
    at org.codehaus.mojo.versions.UseLatestReleasesMojo.update(UseLatestReleasesMojo.java:106)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.process(AbstractVersionsUpdaterMojo.java:322)
    at org.codehaus.mojo.versions.AbstractVersionsUpdaterMojo.execute(AbstractVersionsUpdaterMojo.java:257)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: org.apache.maven.wagon.ResourceDoesNotExistException: File: /rules.xml does not exist
    at org.apache.maven.wagon.providers.file.FileWagon.fillInputData(FileWagon.java:69)
    at org.apache.maven.wagon.StreamWagon.getInputStream(StreamWagon.java:116)
    at org.apache.maven.wagon.StreamWagon.getIfNewer(StreamWagon.java:88)
    at org.apache.maven.wagon.StreamWagon.get(StreamWagon.java:61)
    at org.codehaus.mojo.versions.api.DefaultVersionsHelper.getRuleSet(DefaultVersionsHelper.java:220)
    at org.codehaus.mojo.versions.api.DefaultVersionsHelper.loadRuleSet(DefaultVersionsHelper.java:310)
    ... 29 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by khmarbaise** [comment] 2017-05-22 19:54
Unfortunately I can't reproduce this issue. So I close the issue. If you have further details please don't hesitate to reopen it.

**Closed by khmarbaise** 2017-05-22 19:54 UTC

**Comment by giacgbj** [comment] 2018-01-09 09:34
JFYTK, this problem is related to the lack of "file://" in front of the file path.
